version: "3"
services:
  web:
    image: prosunshining/test_swarm:v0.0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:4000"
    networks:
      - webnet
networks:
  webnet:
